package com.tal.model;

import java.util.Date;

public class BbsReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.reply_id
     *
     * @mbggenerated
     */
    private Long replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.topic_id
     *
     * @mbggenerated
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.reply_dt
     *
     * @mbggenerated
     */
    private Date replyDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.reply_id
     *
     * @return the value of bbs_reply.reply_id
     *
     * @mbggenerated
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.reply_id
     *
     * @param replyId the value for bbs_reply.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.topic_id
     *
     * @return the value of bbs_reply.topic_id
     *
     * @mbggenerated
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.topic_id
     *
     * @param topicId the value for bbs_reply.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.user_id
     *
     * @return the value of bbs_reply.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.user_id
     *
     * @param userId the value for bbs_reply.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.reply_dt
     *
     * @return the value of bbs_reply.reply_dt
     *
     * @mbggenerated
     */
    public Date getReplyDt() {
        return replyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.reply_dt
     *
     * @param replyDt the value for bbs_reply.reply_dt
     *
     * @mbggenerated
     */
    public void setReplyDt(Date replyDt) {
        this.replyDt = replyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.reply_content
     *
     * @return the value of bbs_reply.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.reply_content
     *
     * @param replyContent the value for bbs_reply.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }
}