package com.tal.model;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tal.util.CustomDateTimeSerializer;
import com.tal.util.page.Page;

public class BbsTopic {
	
	private String topicUserName;
	
	private Page page;
	
	private String correct;
	
    public String getCorrect() {
		return correct;
	}

	public void setCorrect(String correct) {
		this.correct = correct;
	}

	public String getTopicUserName() {
		return topicUserName;
	}

	public void setTopicUserName(String topicUserName) {
		this.topicUserName = topicUserName;
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_topic.topic_id
     *
     * @mbggenerated
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_topic.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_topic.lesson_id
     *
     * @mbggenerated
     */
    private Integer lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_topic.topic_name
     *
     * @mbggenerated
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_topic.topic_dt
     *
     * @mbggenerated
     */
    private Date topicDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_topic.topic_id
     *
     * @return the value of bbs_topic.topic_id
     *
     * @mbggenerated
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_topic.topic_id
     *
     * @param topicId the value for bbs_topic.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_topic.user_id
     *
     * @return the value of bbs_topic.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_topic.user_id
     *
     * @param userId the value for bbs_topic.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_topic.lesson_id
     *
     * @return the value of bbs_topic.lesson_id
     *
     * @mbggenerated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_topic.lesson_id
     *
     * @param lessonId the value for bbs_topic.lesson_id
     *
     * @mbggenerated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_topic.topic_name
     *
     * @return the value of bbs_topic.topic_name
     *
     * @mbggenerated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_topic.topic_name
     *
     * @param topicName the value for bbs_topic.topic_name
     *
     * @mbggenerated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_topic.topic_dt
     *
     * @return the value of bbs_topic.topic_dt
     *
     * @mbggenerated
     */
    @JsonSerialize(using=CustomDateTimeSerializer.class)
    public Date getTopicDt() {
        return topicDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_topic.topic_dt
     *
     * @param topicDt the value for bbs_topic.topic_dt
     *
     * @mbggenerated
     */
    public void setTopicDt(Date topicDt) {
        this.topicDt = topicDt;
    }
}