package com.tal.model;

import java.util.Date;

public class Knowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.lesson_id
     *
     * @mbggenerated
     */
    private Integer lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.k_type
     *
     * @mbggenerated
     */
    private String kType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.k_file
     *
     * @mbggenerated
     */
    private String kFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.update_dt
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.id
     *
     * @return the value of knowledge.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.id
     *
     * @param id the value for knowledge.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.lesson_id
     *
     * @return the value of knowledge.lesson_id
     *
     * @mbggenerated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.lesson_id
     *
     * @param lessonId the value for knowledge.lesson_id
     *
     * @mbggenerated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.k_type
     *
     * @return the value of knowledge.k_type
     *
     * @mbggenerated
     */
    public String getkType() {
        return kType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.k_type
     *
     * @param kType the value for knowledge.k_type
     *
     * @mbggenerated
     */
    public void setkType(String kType) {
        this.kType = kType == null ? null : kType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.title
     *
     * @return the value of knowledge.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.title
     *
     * @param title the value for knowledge.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.content
     *
     * @return the value of knowledge.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.content
     *
     * @param content the value for knowledge.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.k_file
     *
     * @return the value of knowledge.k_file
     *
     * @mbggenerated
     */
    public String getkFile() {
        return kFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.k_file
     *
     * @param kFile the value for knowledge.k_file
     *
     * @mbggenerated
     */
    public void setkFile(String kFile) {
        this.kFile = kFile == null ? null : kFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.create_dt
     *
     * @return the value of knowledge.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.create_dt
     *
     * @param createDt the value for knowledge.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.update_dt
     *
     * @return the value of knowledge.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.update_dt
     *
     * @param updateDt the value for knowledge.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}