package com.tal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentWorkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_work
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_work
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_work
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public StudentWorkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_work
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNull() {
            addCriterion("lesson_id is null");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNotNull() {
            addCriterion("lesson_id is not null");
            return (Criteria) this;
        }

        public Criteria andLessonIdEqualTo(Integer value) {
            addCriterion("lesson_id =", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotEqualTo(Integer value) {
            addCriterion("lesson_id <>", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThan(Integer value) {
            addCriterion("lesson_id >", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lesson_id >=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThan(Integer value) {
            addCriterion("lesson_id <", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThanOrEqualTo(Integer value) {
            addCriterion("lesson_id <=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIn(List<Integer> values) {
            addCriterion("lesson_id in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotIn(List<Integer> values) {
            addCriterion("lesson_id not in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdBetween(Integer value1, Integer value2) {
            addCriterion("lesson_id between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lesson_id not between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andWorkIdIsNull() {
            addCriterion("work_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkIdIsNotNull() {
            addCriterion("work_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkIdEqualTo(Long value) {
            addCriterion("work_id =", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotEqualTo(Long value) {
            addCriterion("work_id <>", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThan(Long value) {
            addCriterion("work_id >", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThanOrEqualTo(Long value) {
            addCriterion("work_id >=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThan(Long value) {
            addCriterion("work_id <", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThanOrEqualTo(Long value) {
            addCriterion("work_id <=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdIn(List<Long> values) {
            addCriterion("work_id in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotIn(List<Long> values) {
            addCriterion("work_id not in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdBetween(Long value1, Long value2) {
            addCriterion("work_id between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotBetween(Long value1, Long value2) {
            addCriterion("work_id not between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Double value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Double value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Double value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Double value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Double value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Double> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Double> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Double value1, Double value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Double value1, Double value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andWorkDtIsNull() {
            addCriterion("work_dt is null");
            return (Criteria) this;
        }

        public Criteria andWorkDtIsNotNull() {
            addCriterion("work_dt is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDtEqualTo(Date value) {
            addCriterion("work_dt =", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtNotEqualTo(Date value) {
            addCriterion("work_dt <>", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtGreaterThan(Date value) {
            addCriterion("work_dt >", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtGreaterThanOrEqualTo(Date value) {
            addCriterion("work_dt >=", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtLessThan(Date value) {
            addCriterion("work_dt <", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtLessThanOrEqualTo(Date value) {
            addCriterion("work_dt <=", value, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtIn(List<Date> values) {
            addCriterion("work_dt in", values, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtNotIn(List<Date> values) {
            addCriterion("work_dt not in", values, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtBetween(Date value1, Date value2) {
            addCriterion("work_dt between", value1, value2, "workDt");
            return (Criteria) this;
        }

        public Criteria andWorkDtNotBetween(Date value1, Date value2) {
            addCriterion("work_dt not between", value1, value2, "workDt");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentIsNull() {
            addCriterion("teacher_comment is null");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentIsNotNull() {
            addCriterion("teacher_comment is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentEqualTo(String value) {
            addCriterion("teacher_comment =", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentNotEqualTo(String value) {
            addCriterion("teacher_comment <>", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentGreaterThan(String value) {
            addCriterion("teacher_comment >", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_comment >=", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentLessThan(String value) {
            addCriterion("teacher_comment <", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentLessThanOrEqualTo(String value) {
            addCriterion("teacher_comment <=", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentLike(String value) {
            addCriterion("teacher_comment like", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentNotLike(String value) {
            addCriterion("teacher_comment not like", value, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentIn(List<String> values) {
            addCriterion("teacher_comment in", values, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentNotIn(List<String> values) {
            addCriterion("teacher_comment not in", values, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentBetween(String value1, String value2) {
            addCriterion("teacher_comment between", value1, value2, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andTeacherCommentNotBetween(String value1, String value2) {
            addCriterion("teacher_comment not between", value1, value2, "teacherComment");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathIsNull() {
            addCriterion("work_file_path is null");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathIsNotNull() {
            addCriterion("work_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathEqualTo(String value) {
            addCriterion("work_file_path =", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathNotEqualTo(String value) {
            addCriterion("work_file_path <>", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathGreaterThan(String value) {
            addCriterion("work_file_path >", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("work_file_path >=", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathLessThan(String value) {
            addCriterion("work_file_path <", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathLessThanOrEqualTo(String value) {
            addCriterion("work_file_path <=", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathLike(String value) {
            addCriterion("work_file_path like", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathNotLike(String value) {
            addCriterion("work_file_path not like", value, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathIn(List<String> values) {
            addCriterion("work_file_path in", values, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathNotIn(List<String> values) {
            addCriterion("work_file_path not in", values, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathBetween(String value1, String value2) {
            addCriterion("work_file_path between", value1, value2, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFilePathNotBetween(String value1, String value2) {
            addCriterion("work_file_path not between", value1, value2, "workFilePath");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameIsNull() {
            addCriterion("work_file_name is null");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameIsNotNull() {
            addCriterion("work_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameEqualTo(String value) {
            addCriterion("work_file_name =", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameNotEqualTo(String value) {
            addCriterion("work_file_name <>", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameGreaterThan(String value) {
            addCriterion("work_file_name >", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("work_file_name >=", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameLessThan(String value) {
            addCriterion("work_file_name <", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameLessThanOrEqualTo(String value) {
            addCriterion("work_file_name <=", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameLike(String value) {
            addCriterion("work_file_name like", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameNotLike(String value) {
            addCriterion("work_file_name not like", value, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameIn(List<String> values) {
            addCriterion("work_file_name in", values, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameNotIn(List<String> values) {
            addCriterion("work_file_name not in", values, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameBetween(String value1, String value2) {
            addCriterion("work_file_name between", value1, value2, "workFileName");
            return (Criteria) this;
        }

        public Criteria andWorkFileNameNotBetween(String value1, String value2) {
            addCriterion("work_file_name not between", value1, value2, "workFileName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_work
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_work
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}