package com.tal.model;

public class StudentLesson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_lesson.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_lesson.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_lesson.lesson_id
     *
     * @mbggenerated
     */
    private Integer lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_lesson.total_score
     *
     * @mbggenerated
     */
    private Double totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_lesson.answer_count
     *
     * @mbggenerated
     */
    private Integer answerCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_lesson.id
     *
     * @return the value of student_lesson.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_lesson.id
     *
     * @param id the value for student_lesson.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_lesson.user_id
     *
     * @return the value of student_lesson.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_lesson.user_id
     *
     * @param userId the value for student_lesson.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_lesson.lesson_id
     *
     * @return the value of student_lesson.lesson_id
     *
     * @mbggenerated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_lesson.lesson_id
     *
     * @param lessonId the value for student_lesson.lesson_id
     *
     * @mbggenerated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_lesson.total_score
     *
     * @return the value of student_lesson.total_score
     *
     * @mbggenerated
     */
    public Double getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_lesson.total_score
     *
     * @param totalScore the value for student_lesson.total_score
     *
     * @mbggenerated
     */
    public void setTotalScore(Double totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_lesson.answer_count
     *
     * @return the value of student_lesson.answer_count
     *
     * @mbggenerated
     */
    public Integer getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_lesson.answer_count
     *
     * @param answerCount the value for student_lesson.answer_count
     *
     * @mbggenerated
     */
    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }
}