package com.tal.model;

import java.util.Date;

import com.tal.util.page.Page;

public class TbWork {
	private String workDate1Start;
	
	private String workDate1End;
	
	private Page page;
	
    public String getWorkDate1Start() {
		return workDate1Start;
	}

	public void setWorkDate1Start(String workDate1Start) {
		this.workDate1Start = workDate1Start;
	}

	public String getWorkDate1End() {
		return workDate1End;
	}

	public void setWorkDate1End(String workDate1End) {
		this.workDate1End = workDate1End;
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_id
     *
     * @mbggenerated
     */
    private Long workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.lesson_id
     *
     * @mbggenerated
     */
    private Integer lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_tile
     *
     * @mbggenerated
     */
    private String workTile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_text1
     *
     * @mbggenerated
     */
    private String workText1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_date1
     *
     * @mbggenerated
     */
    private Date workDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.complete_dt
     *
     * @mbggenerated
     */
    private Date completeDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_file
     *
     * @mbggenerated
     */
    private String workFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_id
     *
     * @return the value of tb_work.work_id
     *
     * @mbggenerated
     */
    public Long getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_id
     *
     * @param workId the value for tb_work.work_id
     *
     * @mbggenerated
     */
    public void setWorkId(Long workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.lesson_id
     *
     * @return the value of tb_work.lesson_id
     *
     * @mbggenerated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.lesson_id
     *
     * @param lessonId the value for tb_work.lesson_id
     *
     * @mbggenerated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_tile
     *
     * @return the value of tb_work.work_tile
     *
     * @mbggenerated
     */
    public String getWorkTile() {
        return workTile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_tile
     *
     * @param workTile the value for tb_work.work_tile
     *
     * @mbggenerated
     */
    public void setWorkTile(String workTile) {
        this.workTile = workTile == null ? null : workTile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_text1
     *
     * @return the value of tb_work.work_text1
     *
     * @mbggenerated
     */
    public String getWorkText1() {
        return workText1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_text1
     *
     * @param workText1 the value for tb_work.work_text1
     *
     * @mbggenerated
     */
    public void setWorkText1(String workText1) {
        this.workText1 = workText1 == null ? null : workText1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_date1
     *
     * @return the value of tb_work.work_date1
     *
     * @mbggenerated
     */
    public Date getWorkDate1() {
        return workDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_date1
     *
     * @param workDate1 the value for tb_work.work_date1
     *
     * @mbggenerated
     */
    public void setWorkDate1(Date workDate1) {
        this.workDate1 = workDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.complete_dt
     *
     * @return the value of tb_work.complete_dt
     *
     * @mbggenerated
     */
    public Date getCompleteDt() {
        return completeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.complete_dt
     *
     * @param completeDt the value for tb_work.complete_dt
     *
     * @mbggenerated
     */
    public void setCompleteDt(Date completeDt) {
        this.completeDt = completeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_file
     *
     * @return the value of tb_work.work_file
     *
     * @mbggenerated
     */
    public String getWorkFile() {
        return workFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_file
     *
     * @param workFile the value for tb_work.work_file
     *
     * @mbggenerated
     */
    public void setWorkFile(String workFile) {
        this.workFile = workFile == null ? null : workFile.trim();
    }
}