package com.tal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbWorkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public TbWorkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andWorkIdIsNull() {
            addCriterion("work_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkIdIsNotNull() {
            addCriterion("work_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkIdEqualTo(Long value) {
            addCriterion("work_id =", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotEqualTo(Long value) {
            addCriterion("work_id <>", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThan(Long value) {
            addCriterion("work_id >", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThanOrEqualTo(Long value) {
            addCriterion("work_id >=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThan(Long value) {
            addCriterion("work_id <", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThanOrEqualTo(Long value) {
            addCriterion("work_id <=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdIn(List<Long> values) {
            addCriterion("work_id in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotIn(List<Long> values) {
            addCriterion("work_id not in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdBetween(Long value1, Long value2) {
            addCriterion("work_id between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotBetween(Long value1, Long value2) {
            addCriterion("work_id not between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNull() {
            addCriterion("lesson_id is null");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNotNull() {
            addCriterion("lesson_id is not null");
            return (Criteria) this;
        }

        public Criteria andLessonIdEqualTo(Integer value) {
            addCriterion("lesson_id =", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotEqualTo(Integer value) {
            addCriterion("lesson_id <>", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThan(Integer value) {
            addCriterion("lesson_id >", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lesson_id >=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThan(Integer value) {
            addCriterion("lesson_id <", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThanOrEqualTo(Integer value) {
            addCriterion("lesson_id <=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIn(List<Integer> values) {
            addCriterion("lesson_id in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotIn(List<Integer> values) {
            addCriterion("lesson_id not in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdBetween(Integer value1, Integer value2) {
            addCriterion("lesson_id between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lesson_id not between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andWorkTileIsNull() {
            addCriterion("work_tile is null");
            return (Criteria) this;
        }

        public Criteria andWorkTileIsNotNull() {
            addCriterion("work_tile is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTileEqualTo(String value) {
            addCriterion("work_tile =", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileNotEqualTo(String value) {
            addCriterion("work_tile <>", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileGreaterThan(String value) {
            addCriterion("work_tile >", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileGreaterThanOrEqualTo(String value) {
            addCriterion("work_tile >=", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileLessThan(String value) {
            addCriterion("work_tile <", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileLessThanOrEqualTo(String value) {
            addCriterion("work_tile <=", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileLike(String value) {
            addCriterion("work_tile like", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileNotLike(String value) {
            addCriterion("work_tile not like", value, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileIn(List<String> values) {
            addCriterion("work_tile in", values, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileNotIn(List<String> values) {
            addCriterion("work_tile not in", values, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileBetween(String value1, String value2) {
            addCriterion("work_tile between", value1, value2, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkTileNotBetween(String value1, String value2) {
            addCriterion("work_tile not between", value1, value2, "workTile");
            return (Criteria) this;
        }

        public Criteria andWorkText1IsNull() {
            addCriterion("work_text1 is null");
            return (Criteria) this;
        }

        public Criteria andWorkText1IsNotNull() {
            addCriterion("work_text1 is not null");
            return (Criteria) this;
        }

        public Criteria andWorkText1EqualTo(String value) {
            addCriterion("work_text1 =", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1NotEqualTo(String value) {
            addCriterion("work_text1 <>", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1GreaterThan(String value) {
            addCriterion("work_text1 >", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1GreaterThanOrEqualTo(String value) {
            addCriterion("work_text1 >=", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1LessThan(String value) {
            addCriterion("work_text1 <", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1LessThanOrEqualTo(String value) {
            addCriterion("work_text1 <=", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1Like(String value) {
            addCriterion("work_text1 like", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1NotLike(String value) {
            addCriterion("work_text1 not like", value, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1In(List<String> values) {
            addCriterion("work_text1 in", values, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1NotIn(List<String> values) {
            addCriterion("work_text1 not in", values, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1Between(String value1, String value2) {
            addCriterion("work_text1 between", value1, value2, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkText1NotBetween(String value1, String value2) {
            addCriterion("work_text1 not between", value1, value2, "workText1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1IsNull() {
            addCriterion("work_date1 is null");
            return (Criteria) this;
        }

        public Criteria andWorkDate1IsNotNull() {
            addCriterion("work_date1 is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDate1EqualTo(Date value) {
            addCriterionForJDBCDate("work_date1 =", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1NotEqualTo(Date value) {
            addCriterionForJDBCDate("work_date1 <>", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1GreaterThan(Date value) {
            addCriterionForJDBCDate("work_date1 >", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_date1 >=", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1LessThan(Date value) {
            addCriterionForJDBCDate("work_date1 <", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_date1 <=", value, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1In(List<Date> values) {
            addCriterionForJDBCDate("work_date1 in", values, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1NotIn(List<Date> values) {
            addCriterionForJDBCDate("work_date1 not in", values, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1Between(Date value1, Date value2) {
            addCriterionForJDBCDate("work_date1 between", value1, value2, "workDate1");
            return (Criteria) this;
        }

        public Criteria andWorkDate1NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_date1 not between", value1, value2, "workDate1");
            return (Criteria) this;
        }

        public Criteria andCompleteDtIsNull() {
            addCriterion("complete_dt is null");
            return (Criteria) this;
        }

        public Criteria andCompleteDtIsNotNull() {
            addCriterion("complete_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteDtEqualTo(Date value) {
            addCriterionForJDBCDate("complete_dt =", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("complete_dt <>", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtGreaterThan(Date value) {
            addCriterionForJDBCDate("complete_dt >", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("complete_dt >=", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtLessThan(Date value) {
            addCriterionForJDBCDate("complete_dt <", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("complete_dt <=", value, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtIn(List<Date> values) {
            addCriterionForJDBCDate("complete_dt in", values, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("complete_dt not in", values, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("complete_dt between", value1, value2, "completeDt");
            return (Criteria) this;
        }

        public Criteria andCompleteDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("complete_dt not between", value1, value2, "completeDt");
            return (Criteria) this;
        }

        public Criteria andWorkFileIsNull() {
            addCriterion("work_file is null");
            return (Criteria) this;
        }

        public Criteria andWorkFileIsNotNull() {
            addCriterion("work_file is not null");
            return (Criteria) this;
        }

        public Criteria andWorkFileEqualTo(String value) {
            addCriterion("work_file =", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileNotEqualTo(String value) {
            addCriterion("work_file <>", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileGreaterThan(String value) {
            addCriterion("work_file >", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileGreaterThanOrEqualTo(String value) {
            addCriterion("work_file >=", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileLessThan(String value) {
            addCriterion("work_file <", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileLessThanOrEqualTo(String value) {
            addCriterion("work_file <=", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileLike(String value) {
            addCriterion("work_file like", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileNotLike(String value) {
            addCriterion("work_file not like", value, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileIn(List<String> values) {
            addCriterion("work_file in", values, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileNotIn(List<String> values) {
            addCriterion("work_file not in", values, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileBetween(String value1, String value2) {
            addCriterion("work_file between", value1, value2, "workFile");
            return (Criteria) this;
        }

        public Criteria andWorkFileNotBetween(String value1, String value2) {
            addCriterion("work_file not between", value1, value2, "workFile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}