package com.tal.model;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tal.util.CustomDateTimeSerializer;
import com.tal.util.page.Page;

public class TbWork {
	
	private String workDate1Start;
	private String workDate1End;
	
	
	public String getWorkDate1Start() {
		return workDate1Start;
	}

	public void setWorkDate1Start(String workDate1Start) {
		this.workDate1Start = workDate1Start;
	}

	public String getWorkDate1End() {
		return workDate1End;
	}

	public void setWorkDate1End(String workDate1End) {
		this.workDate1End = workDate1End;
	}

	private Page page;
    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_id
     *
     * @mbggenerated
     */
    private Long workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_tile
     *
     * @mbggenerated
     */
    private String workTile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_text1
     *
     * @mbggenerated
     */
    private String workText1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work.work_date1
     *
     * @mbggenerated
     */
    private Date workDate1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_id
     *
     * @return the value of tb_work.work_id
     *
     * @mbggenerated
     */
    public Long getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_id
     *
     * @param workId the value for tb_work.work_id
     *
     * @mbggenerated
     */
    public void setWorkId(Long workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.user_id
     *
     * @return the value of tb_work.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.user_id
     *
     * @param userId the value for tb_work.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_tile
     *
     * @return the value of tb_work.work_tile
     *
     * @mbggenerated
     */
    public String getWorkTile() {
        return workTile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_tile
     *
     * @param workTile the value for tb_work.work_tile
     *
     * @mbggenerated
     */
    public void setWorkTile(String workTile) {
        this.workTile = workTile == null ? null : workTile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_text1
     *
     * @return the value of tb_work.work_text1
     *
     * @mbggenerated
     */
    public String getWorkText1() {
        return workText1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_text1
     *
     * @param workText1 the value for tb_work.work_text1
     *
     * @mbggenerated
     */
    public void setWorkText1(String workText1) {
        this.workText1 = workText1 == null ? null : workText1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work.work_date1
     *
     * @return the value of tb_work.work_date1
     *
     * @mbggenerated
     */
    @JsonSerialize(using=CustomDateTimeSerializer.class)
    public Date getWorkDate1() {
        return workDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work.work_date1
     *
     * @param workDate1 the value for tb_work.work_date1
     *
     * @mbggenerated
     */
    public void setWorkDate1(Date workDate1) {
        this.workDate1 = workDate1;
    }
}