package com.tal.model;

public class TeacherLesson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_lesson.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_lesson.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_lesson.lesson_id
     *
     * @mbggenerated
     */
    private Integer lessonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_lesson.id
     *
     * @return the value of teacher_lesson.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_lesson.id
     *
     * @param id the value for teacher_lesson.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_lesson.user_id
     *
     * @return the value of teacher_lesson.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_lesson.user_id
     *
     * @param userId the value for teacher_lesson.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_lesson.lesson_id
     *
     * @return the value of teacher_lesson.lesson_id
     *
     * @mbggenerated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_lesson.lesson_id
     *
     * @param lessonId the value for teacher_lesson.lesson_id
     *
     * @mbggenerated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }
}