package com.tal.user.service;

import org.apache.ibatis.annotations.Param;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tal.dao.TbUserMapper;
import com.tal.model.TbUser;
import com.tal.model.TbUserExample;

@Service
public class UserService {

	@Autowired
	TbUserMapper mapper;
	

	public int deleteByPrimaryKey(Integer userId){
		return mapper.deleteByPrimaryKey(userId);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public int insert(TbUser record){
    	return mapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public int insertSelective(TbUser record){
    	return mapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public TbUser selectByPrimaryKey(Integer userId){
    	return mapper.selectByPrimaryKey(userId);
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(TbUser record){
    	return mapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(TbUser record){
    	return mapper.updateByPrimaryKey(record);
    }
    
    public TbUser selectByNameAndPwd(TbUser record){
    	return mapper.selectByNameAndPwd(record);
    }
}
