package com.tal.dao;

import com.tal.model.BbsReply;
import com.tal.model.BbsReplyExample;
import org.apache.ibatis.annotations.Param;

public interface BbsReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int deleteByExample(BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int insert(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int insertSelective(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    BbsReply selectByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbsReply record);
}