package com.tal.dao;

import com.tal.model.BbsTopic;
import com.tal.model.BbsTopicExample;
import org.apache.ibatis.annotations.Param;

public interface BbsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int deleteByExample(BbsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int insert(BbsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int insertSelective(BbsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    BbsTopic selectByPrimaryKey(Long topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbsTopic record, @Param("example") BbsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbsTopic record, @Param("example") BbsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbsTopic record);
}