package com.tal.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tal.model.Lesson;
import com.tal.model.LessonExample;

public interface LessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int deleteByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lessonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    Lesson selectByPrimaryKey(Integer lessonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lesson record);
    
    List<Lesson> listPageLesson(Lesson record);
    
    List<Lesson> getLessons(String role,Integer userId);
}