package com.tal.dao;

import com.tal.model.StudentLesson;
import com.tal.model.StudentLessonExample;
import org.apache.ibatis.annotations.Param;

public interface StudentLessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int deleteByExample(StudentLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int insert(StudentLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int insertSelective(StudentLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    StudentLesson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudentLesson record, @Param("example") StudentLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudentLesson record, @Param("example") StudentLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentLesson record);
    
    int deleteByLesson(Integer lessonId);
}