package com.tal.dao;

import com.tal.model.TeacherLesson;
import com.tal.model.TeacherLessonExample;
import org.apache.ibatis.annotations.Param;

public interface TeacherLessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int deleteByExample(TeacherLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int insert(TeacherLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int insertSelective(TeacherLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    TeacherLesson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeacherLesson record, @Param("example") TeacherLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeacherLesson record, @Param("example") TeacherLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherLesson record);
    
    int deleteByTearchAndLesson(int teacherId,int lessonId);
}